apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic-visits-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/devops22clc/spring-petclinic-microservices-ops
    targetRevision: HEAD
    path: spring-petclinic-visits-service/overlay/dev
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  imageUpdater:
    enable: true
    tag: latest