apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: visits-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/devops22clc/spring-petclinic-microservices-ops
    targetRevision: HEAD
    path: spring-petclinic-visits-service/overlay/staging
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
