apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic-genai-service-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/devops22clc/spring-petclinic-microservices-ops.git
    path: spring-petclinic-genai-service/overlay/prod
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      releaseName: genai-service
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true