apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic-customers-service-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/devops22clc/spring-petclinic-microservices-ops.git
    path: spring-petclinic-customers-service/overlay/staging
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      releaseName: customers-service
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true