apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: discovery-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/devops22clc/spring-petclinic-microservices-ops
    targetRevision: HEAD
    path: spring-petclinic-discovery-server/overlay/prod
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
