apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic-customers-service-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: customers-service=devops22clc/spring-petclinic-customers-service
    argocd-image-updater.argoproj.io/update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/devops22clc/spring-petclinic-microservices-ops.git
    path: spring-petclinic-customers-service/overlay/dev
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      releaseName: customers-service
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
